apiVersion: apps/v1
kind: Services
metadata:
  labels:
    app: nginx
  name: nginx-services
  namespace: default
spec:
  ports:
  - port: 80
    protocal: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
